//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soulstone.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.PlaylistSongs = new HashSet<PlaylistSong>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Album { get; set; }
        public string Artist { get; set; }
        public Nullable<int> Year { get; set; }
        public string Genre { get; set; }
        public System.TimeSpan Duration { get; set; }
        public byte[] Artwork { get; set; }
        public int Bitrate { get; set; }
        public string Hash { get; set; }
        public string FileName { get; set; }
    
        public virtual ICollection<PlaylistSong> PlaylistSongs { get; set; }
    }
}
